[2023-12-18 06:59:12,926: INFO: main: Welcome to our custom log]
[2023-12-26 18:37:41,428: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-26 18:37:41,594: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-26 18:37:41,628: INFO: common: created directory at: artifacts]
[2023-12-26 18:37:41,634: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-26 18:37:41,646: INFO: 986331348: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-26 18:38:39,410: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-26 18:57:21,116: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2023-12-26 18:57:21,118: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-26 18:57:21,119: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-26 18:57:21,120: INFO: common: created directory at: artifacts]
[2023-12-26 18:57:21,121: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-26 18:57:21,122: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-26 19:01:04,331: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-26 19:01:05,844: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2023-12-30 13:55:44,600: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-30 13:55:44,718: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-30 13:55:44,778: INFO: common: created directory at: artifacts]
[2023-12-30 13:55:44,780: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-30 13:56:12,678: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-30 14:20:13,694: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2023-12-30 14:20:13,696: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-30 14:20:13,698: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-30 14:20:13,698: INFO: common: created directory at: artifacts]
[2023-12-30 14:20:13,699: INFO: common: created directory at: artifacts/data_ingestion]
[2023-12-30 14:20:13,699: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-30 14:20:43,854: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-30 14:20:45,316: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2023-12-30 14:20:45,316: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2023-12-30 14:20:45,320: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-12-30 14:20:45,321: INFO: common: yaml file: params.yaml loaded successfully]
[2023-12-30 14:20:45,323: INFO: common: created directory at: artifacts]
[2023-12-30 14:20:45,324: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-12-30 14:20:53,131: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-30 14:20:54,380: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2024-01-09 11:18:17,918: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-09 11:18:17,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-09 11:18:17,997: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-09 11:18:18,037: INFO: common: created directory at: artifacts]
[2024-01-09 11:18:18,038: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-09 11:18:18,039: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-09 11:18:20,837: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-09 11:18:25,607: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-01-09 11:18:25,608: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2024-01-09 11:18:25,611: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-09 11:18:25,613: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-09 11:18:25,614: INFO: common: created directory at: artifacts]
[2024-01-09 11:18:25,614: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-09 11:18:44,216: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-09 11:18:48,191: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2024-01-09 11:18:48,192: INFO: main: *******************]
[2024-01-09 11:18:48,197: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-09 11:18:48,206: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-09 11:18:48,212: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-09 11:18:48,214: INFO: common: created directory at: artifacts]
[2024-01-09 11:18:48,215: INFO: common: created directory at: artifacts\training]
[2024-01-09 11:44:31,069: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-09 11:44:31,071: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-09 11:44:31,180: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-09 11:44:31,180: INFO: common: created directory at: artifacts]
[2024-01-09 11:44:31,181: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-09 11:44:31,184: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-09 11:44:57,917: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-09 11:44:59,325: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-01-09 11:44:59,325: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2024-01-09 11:44:59,335: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-09 11:44:59,338: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-09 11:44:59,339: INFO: common: created directory at: artifacts]
[2024-01-09 11:44:59,340: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-09 11:45:01,983: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-09 11:45:03,201: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2024-01-09 11:45:03,201: INFO: main: *******************]
[2024-01-09 11:45:03,203: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-09 11:45:03,210: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-09 11:45:03,212: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-09 11:45:03,213: INFO: common: created directory at: artifacts]
[2024-01-09 11:45:03,214: INFO: common: created directory at: artifacts\training]
[2024-01-09 12:05:07,314: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-01-12 20:50:11,821: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 20:50:11,885: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 20:50:11,890: INFO: common: created directory at: artifacts]
[2024-01-12 20:50:45,385: INFO: common: json file saved at: scores.json]
[2024-01-12 20:50:51,095: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-01-12 20:50:53,609: INFO: builder_impl: Assets written to: C:\Users\SHERIF~1\AppData\Local\Temp\tmp3laf7su2\model\data\model\assets]
[2024-01-12 21:08:00,186: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 21:08:00,206: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 21:08:00,209: INFO: common: created directory at: artifacts]
[2024-01-12 21:08:20,645: INFO: common: json file saved at: scores.json]
[2024-01-12 21:08:24,269: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-01-12 21:08:25,619: INFO: builder_impl: Assets written to: C:\Users\SHERIF~1\AppData\Local\Temp\tmp90s1pv0e\model\data\model\assets]
[2024-01-12 21:31:01,547: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-12 21:31:01,555: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 21:31:01,563: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 21:31:01,563: INFO: common: created directory at: artifacts]
[2024-01-12 21:31:01,564: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-12 21:31:01,566: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 21:31:03,374: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 21:31:03,376: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\main.py", line 13, in <module>
    obj.main()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1239, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-01-12 21:31:21,476: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-12 21:31:21,480: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 21:31:21,482: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 21:31:21,483: INFO: common: created directory at: artifacts]
[2024-01-12 21:31:21,484: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-12 21:31:21,484: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 21:31:22,419: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 21:31:22,421: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\main.py", line 13, in <module>
    obj.main()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1239, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-01-12 21:33:39,413: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-12 21:33:39,416: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 21:33:39,417: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 21:33:39,417: INFO: common: created directory at: artifacts]
[2024-01-12 21:33:39,418: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-12 21:33:39,418: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 21:33:40,005: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 21:33:40,006: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\main.py", line 13, in <module>
    obj.main()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1239, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-01-12 21:34:47,979: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-12 21:34:47,981: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 21:34:47,983: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 21:34:47,984: INFO: common: created directory at: artifacts]
[2024-01-12 21:34:48,030: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-12 21:34:48,032: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 21:34:48,704: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 21:34:48,705: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\main.py", line 13, in <module>
    obj.main()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1239, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-01-12 21:36:00,365: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 21:36:00,389: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 21:36:00,391: INFO: common: created directory at: artifacts]
[2024-01-12 21:36:00,393: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-12 21:36:00,396: INFO: 986331348: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 21:36:01,226: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 21:55:28,075: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-12 21:55:28,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 21:55:28,093: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 21:55:28,094: INFO: common: created directory at: artifacts]
[2024-01-12 21:55:28,095: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-12 21:55:28,096: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 21:55:29,348: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 21:55:33,772: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-01-12 21:55:33,772: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2024-01-12 21:55:33,776: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 21:55:33,778: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 21:55:33,778: INFO: common: created directory at: artifacts]
[2024-01-12 21:55:33,779: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-12 21:55:57,281: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-12 21:56:05,646: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2024-01-12 21:56:05,647: INFO: main: *******************]
[2024-01-12 21:56:05,651: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-12 21:56:05,659: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 21:56:05,660: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 21:56:05,661: INFO: common: created directory at: artifacts]
[2024-01-12 21:56:05,661: INFO: common: created directory at: artifacts\training]
[2024-01-12 22:12:42,618: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-01-12 22:12:42,622: INFO: main: *******************]
[2024-01-12 22:12:42,626: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<]
[2024-01-12 22:12:42,663: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:12:42,665: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:12:42,740: INFO: common: created directory at: artifacts]
[2024-01-12 22:13:07,188: INFO: common: json file saved at: scores.json]
[2024-01-12 22:13:07,190: INFO: common: json file saved at: scores.json]
[2024-01-12 22:13:07,190: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<

x==========x]
[2024-01-12 22:15:50,598: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-12 22:15:50,601: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:15:50,636: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:15:50,637: INFO: common: created directory at: artifacts]
[2024-01-12 22:15:50,637: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-12 22:15:50,638: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 22:15:51,365: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 22:15:55,856: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-01-12 22:15:55,856: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2024-01-12 22:15:55,858: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:15:55,860: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:15:55,861: INFO: common: created directory at: artifacts]
[2024-01-12 22:15:55,862: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-12 22:15:59,522: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-12 22:16:03,566: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2024-01-12 22:16:03,566: INFO: main: *******************]
[2024-01-12 22:16:03,568: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-12 22:16:03,573: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:16:03,574: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:16:03,575: INFO: common: created directory at: artifacts]
[2024-01-12 22:16:03,576: INFO: common: created directory at: artifacts\training]
[2024-01-12 22:24:50,562: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-01-12 22:24:50,562: INFO: main: *******************]
[2024-01-12 22:24:50,565: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<]
[2024-01-12 22:24:50,570: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:24:50,572: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:24:50,573: INFO: common: created directory at: artifacts]
[2024-01-12 22:25:08,668: INFO: common: json file saved at: scores.json]
[2024-01-12 22:25:08,669: INFO: common: json file saved at: scores.json]
[2024-01-12 22:25:08,669: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<

x==========x]
[2024-01-12 22:28:05,869: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-12 22:28:05,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:28:05,883: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:28:05,884: INFO: common: created directory at: artifacts]
[2024-01-12 22:28:05,885: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-12 22:28:05,885: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 22:28:06,633: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 22:28:07,939: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-01-12 22:28:07,940: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2024-01-12 22:28:07,944: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:28:07,946: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:28:07,946: INFO: common: created directory at: artifacts]
[2024-01-12 22:28:07,947: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-12 22:28:08,700: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-12 22:28:12,133: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2024-01-12 22:28:12,134: INFO: main: *******************]
[2024-01-12 22:28:12,138: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-12 22:28:12,143: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:28:12,145: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:28:12,146: INFO: common: created directory at: artifacts]
[2024-01-12 22:28:12,147: INFO: common: created directory at: artifacts\training]
[2024-01-12 22:36:10,307: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-01-12 22:36:10,308: INFO: main: *******************]
[2024-01-12 22:36:10,309: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<]
[2024-01-12 22:36:10,313: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:36:10,315: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:36:10,315: INFO: common: created directory at: artifacts]
[2024-01-12 22:36:28,459: INFO: common: json file saved at: scores.json]
[2024-01-12 22:36:28,460: INFO: common: json file saved at: scores.json]
[2024-01-12 22:36:31,663: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-01-12 22:36:33,614: INFO: builder_impl: Assets written to: C:\Users\SHERIF~1\AppData\Local\Temp\tmpgxfq5fs3\model\data\model\assets]
[2024-01-12 22:37:14,102: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<

x==========x]
[2024-01-12 22:46:16,801: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-12 22:46:16,819: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:46:16,822: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:46:16,823: INFO: common: created directory at: artifacts]
[2024-01-12 22:46:16,824: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-12 22:46:16,824: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 22:46:17,877: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 22:46:18,965: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-01-12 22:46:18,965: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2024-01-12 22:46:18,970: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:46:18,972: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:46:18,972: INFO: common: created directory at: artifacts]
[2024-01-12 22:46:18,973: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-12 22:46:19,480: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-12 22:46:24,795: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2024-01-12 22:46:24,796: INFO: main: *******************]
[2024-01-12 22:46:24,798: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-12 22:46:24,803: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:46:24,805: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:46:24,806: INFO: common: created directory at: artifacts]
[2024-01-12 22:46:24,808: INFO: common: created directory at: artifacts\training]
[2024-01-12 22:54:10,721: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-01-12 22:54:10,722: INFO: main: *******************]
[2024-01-12 22:54:10,723: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<]
[2024-01-12 22:54:10,728: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:54:10,731: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:54:10,731: INFO: common: created directory at: artifacts]
[2024-01-12 22:54:28,816: INFO: common: json file saved at: scores.json]
[2024-01-12 22:54:28,818: INFO: common: json file saved at: scores.json]
[2024-01-12 22:54:31,600: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-01-12 22:54:33,285: INFO: builder_impl: Assets written to: C:\Users\SHERIF~1\AppData\Local\Temp\tmp25tgcc2j\model\data\model\assets]
[2024-01-12 22:58:05,717: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<

x==========x]
[2024-01-12 22:58:59,265: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-12 22:58:59,268: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:58:59,295: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:58:59,297: INFO: common: created directory at: artifacts]
[2024-01-12 22:58:59,302: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-12 22:58:59,303: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 22:59:00,132: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11JSzIggqryIUf5g62FNonYboVdKiDhhu/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-12 22:59:01,319: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-01-12 22:59:01,319: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2024-01-12 22:59:01,323: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:59:01,325: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:59:01,325: INFO: common: created directory at: artifacts]
[2024-01-12 22:59:01,326: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-12 22:59:01,811: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-12 22:59:06,134: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2024-01-12 22:59:06,135: INFO: main: *******************]
[2024-01-12 22:59:06,136: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-12 22:59:06,140: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 22:59:06,142: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 22:59:06,143: INFO: common: created directory at: artifacts]
[2024-01-12 22:59:06,144: INFO: common: created directory at: artifacts\training]
[2024-01-12 23:02:59,052: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-01-12 23:02:59,053: INFO: main: *******************]
[2024-01-12 23:02:59,072: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<]
[2024-01-12 23:02:59,075: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-12 23:02:59,077: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-12 23:02:59,078: INFO: common: created directory at: artifacts]
[2024-01-12 23:03:17,473: INFO: common: json file saved at: scores.json]
[2024-01-12 23:03:17,475: INFO: common: json file saved at: scores.json]
[2024-01-12 23:03:20,338: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-01-12 23:03:21,695: INFO: builder_impl: Assets written to: C:\Users\SHERIF~1\AppData\Local\Temp\tmpyaggtcc3\model\data\model\assets]
[2024-01-12 23:05:35,933: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<

x==========x]
[2024-01-13 22:42:37,041: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-13 22:42:37,054: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-13 22:42:37,075: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-13 22:42:37,076: INFO: common: created directory at: artifacts]
[2024-01-13 22:42:37,079: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-13 22:42:37,080: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-13 22:42:38,208: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-13 22:42:38,212: ERROR: stage_01_data_ingestion: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 24, in <module>
    obj.main()
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1239, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-01-13 22:47:57,560: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-13 22:47:57,563: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-13 22:47:57,565: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-13 22:47:57,566: INFO: common: created directory at: artifacts]
[2024-01-13 22:47:57,567: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-13 22:47:57,568: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-13 22:47:58,103: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-13 22:47:58,105: ERROR: stage_01_data_ingestion: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 24, in <module>
    obj.main()
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1239, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-01-13 22:53:39,598: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-13 22:53:39,601: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-13 22:53:39,603: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-13 22:53:39,604: INFO: common: created directory at: artifacts]
[2024-01-13 22:53:39,605: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-13 22:53:39,605: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-13 22:53:40,668: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-13 22:53:40,669: ERROR: stage_01_data_ingestion: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 24, in <module>
    obj.main()
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1239, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-01-14 00:06:42,651: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-14 00:06:42,665: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-14 00:06:42,715: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-14 00:06:42,716: INFO: common: created directory at: artifacts]
[2024-01-14 00:06:42,717: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-14 00:06:42,719: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1MHgBD8HzN9Tez_XKZXd78ib1TAukWagy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-14 00:06:44,412: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1MHgBD8HzN9Tez_XKZXd78ib1TAukWagy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-14 00:06:44,413: ERROR: stage_01_data_ingestion: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 24, in <module>
    obj.main()
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1239, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-01-14 00:12:30,727: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-14 00:12:30,749: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-14 00:12:30,751: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-14 00:12:30,752: INFO: common: created directory at: artifacts]
[2024-01-14 00:12:30,753: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-14 00:12:30,754: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1MHgBD8HzN9Tez_XKZXd78ib1TAukWagy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-14 00:12:31,934: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1MHgBD8HzN9Tez_XKZXd78ib1TAukWagy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-14 00:12:33,045: ERROR: stage_01_data_ingestion: File is not a zip file]
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 24, in <module>
    obj.main()
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 45, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-01-14 00:16:36,690: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-14 00:16:36,692: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-14 00:16:36,695: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-14 00:16:36,697: INFO: common: created directory at: artifacts]
[2024-01-14 00:16:36,698: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-14 00:16:36,699: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1MHgBD8HzN9Tez_XKZXd78ib1TAukWagy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-14 00:16:37,838: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1MHgBD8HzN9Tez_XKZXd78ib1TAukWagy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-14 00:16:37,840: ERROR: stage_01_data_ingestion: File is not a zip file]
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 24, in <module>
    obj.main()
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-01-14 00:29:02,133: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-14 00:29:02,158: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-14 00:29:02,183: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-14 00:29:02,185: INFO: common: created directory at: artifacts]
[2024-01-14 00:29:02,188: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-14 00:29:02,190: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1MHgBD8HzN9Tez_XKZXd78ib1TAukWagy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-14 00:29:03,419: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1MHgBD8HzN9Tez_XKZXd78ib1TAukWagy/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-14 00:29:03,432: ERROR: stage_01_data_ingestion: File is not a zip file]
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 24, in <module>
    obj.main()
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "C:\Users\SHERIF ATITEBI O\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-01-14 00:43:59,765: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-01-14 00:43:59,781: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-14 00:43:59,802: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-14 00:43:59,803: INFO: common: created directory at: artifacts]
[2024-01-14 00:43:59,804: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-14 00:43:59,806: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1UobrnxGapkb2PYzsfuM75VkYVf-fRaqG/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-14 00:45:36,205: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1UobrnxGapkb2PYzsfuM75VkYVf-fRaqG/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-14 00:45:59,180: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-01-14 00:48:43,007: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model started <<<<<<]
[2024-01-14 00:48:43,024: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-14 00:48:43,025: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-14 00:48:43,026: INFO: common: created directory at: artifacts]
[2024-01-14 00:48:43,027: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-14 00:48:46,773: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-14 00:48:47,196: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2024-01-14 00:49:08,089: INFO: stage_03_model_training: *******************]
[2024-01-14 00:49:08,090: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-01-14 00:49:08,094: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-14 00:49:08,096: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-14 00:49:08,097: INFO: common: created directory at: artifacts]
[2024-01-14 00:49:08,098: INFO: common: created directory at: artifacts\training]
[2024-01-14 01:27:08,362: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-01-14 01:28:10,842: INFO: stage_04_model_evaluation: *******************]
[2024-01-14 01:28:10,842: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation Stage started <<<<<<]
[2024-01-14 01:28:10,846: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-14 01:28:10,849: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-14 01:28:10,850: INFO: common: created directory at: artifacts]
[2024-01-14 01:29:18,241: INFO: common: json file saved at: scores.json]
[2024-01-14 01:29:18,243: INFO: common: json file saved at: scores.json]
[2024-01-14 01:29:21,429: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-01-14 01:29:23,069: INFO: builder_impl: Assets written to: C:\Users\SHERIF~1\AppData\Local\Temp\tmpei4c_xs6\model\data\model\assets]
[2024-01-14 01:29:56,229: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation Stage completed <<<<<<

x==========x]
[2024-01-14 01:34:55,101: INFO: stage_04_model_evaluation: ******************]
[2024-01-14 01:34:55,102: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation Stage started <<<<<<]
[2024-01-14 01:34:55,106: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-14 01:34:55,108: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-14 01:34:55,109: INFO: common: created directory at: artifacts]
[2024-01-14 01:36:03,533: INFO: common: json file saved at: scores.json]
[2024-01-14 01:36:03,534: INFO: common: json file saved at: scores.json]
[2024-01-14 01:36:07,274: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-01-14 01:36:08,870: INFO: builder_impl: Assets written to: C:\Users\SHERIF~1\AppData\Local\Temp\tmp1m_p75l0\model\data\model\assets]
[2024-01-14 01:37:20,010: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation Stage completed <<<<<<

x==========x]
[2024-01-15 15:56:33,893: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3000
 * Running on http://10.0.52.49:3000]
[2024-01-15 15:56:33,916: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-01-15 15:57:35,328: INFO: _internal: 127.0.0.1 - - [15/Jan/2024 15:57:35] "GET / HTTP/1.1" 200 -]
[2024-01-15 15:58:04,574: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-01-15 15:58:05,020: INFO: _internal: 127.0.0.1 - - [15/Jan/2024 15:58:05] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-01-15 16:02:29,375: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3000
 * Running on http://10.0.52.49:3000]
[2024-01-15 16:02:29,377: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-01-15 16:02:37,349: INFO: _internal: 127.0.0.1 - - [15/Jan/2024 16:02:37] "GET / HTTP/1.1" 200 -]
[2024-01-15 16:02:50,586: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\sherif atitebi o\documents\kidney-disease-classification-project\src\kidneyDiseaseClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("training", "model.h5"))
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\SHERIF ATITEBI O\Documents\Kidney-Disease-Classification-Project\virtualenv\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at training\model.h5
[2024-01-15 16:02:50,598: INFO: _internal: 127.0.0.1 - - [15/Jan/2024 16:02:50] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-01-15 16:05:05,372: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3000
 * Running on http://10.0.52.49:3000]
[2024-01-15 16:05:05,374: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-01-15 16:05:10,636: INFO: _internal: 127.0.0.1 - - [15/Jan/2024 16:05:10] "GET / HTTP/1.1" 200 -]
[2024-01-15 16:05:29,886: INFO: _internal: 127.0.0.1 - - [15/Jan/2024 16:05:29] "POST /predict HTTP/1.1" 200 -]
